-- AlterTable
ALTER TABLE "LocationHistory" ADD COLUMN     "accel_x" DOUBLE PRECISION,
ADD COLUMN     "accel_y" DOUBLE PRECISION,
ADD COLUMN     "accel_z" DOUBLE PRECISION,
ALTER COLUMN "lat" DROP NOT NULL,
ALTER COLUMN "lng" DROP NOT NULL;
